/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'service' : string,
  'status' : Status,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'dateTime' : string,
}
export type Status = { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  'createAppointment' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getAppointmentsByStatus' : ActorMethod<[Status], Array<Appointment>>,
  'isAppointmentOwner' : ActorMethod<[bigint], boolean>,
  'updateAppointmentStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];